apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.repository.name }}-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: {{ .Values.repository.url }}
